#+TITLE: Primer parcial INF 324

| Nombre: | Jesus Rodolfo Izurieta Veliz |
| CI:     |                      9860616 |

* Enunciado
1. Usted ha definido una tabla IDENTIFICADOR en la base de datos ACADEMICO, la
   cual contiene información de CI, Nombre completo, fecha de nacimiento, lugar
   de residencia (codigo) (El dato suyo es inicial, aunque el numero de carnet
   de sus amigos sean menores); otra tabla denominada USUARIO con los datos de
   CI y clave; realice lo siguiente: Genere un login por cada CI, ingresando a
   una pantalla de bienvenida (cuya cabecera indicara el nombre de su pagina,
   con una foto de usted con CSS) y un color por defecto (PHP), incluya un INPUT
   de tipo select que tenga al menos tres colores.

2. Con la Base de datos anterior, adicione una tabla de notas por materia y
   cuente la cantidad de aprobados por departamento de manera que solo obtenga
   una sola fila de resultados (con codigo PHP, con codigo SQL) Una vez
   desarrollado, en un archivo Word o PDF indique el link por cada pregunta.
  
* Instrucciones
** Docker
Para iniciar el proyecto con docker, se necesita tener instalado docker:

[[https://docs.docker.com/engine/install/][Instalación de docker]]

Y docker-compose:

[[https://docs.docker.com/compose/install/][Instalación de docker-compose]]

Después de esto, el servidor se inicia con el comando =docker-compose up= y el
proyecto estará corriendo en el puerto 8000.

** XAMPP
En caso de no instalar docker, el proyecto puede inicializarse usando XAMPP,
para lo cual, el directorio =parcial1= tendrá que copiarse a =htdocs=.

* Estructura del proyecto
El proyecto consta de dos secciones para resolver los dos problemas propuestos
en el enunciado.
- Inicio de sesión :: Para el inicio de sesión se ingresa en la dirección raíz
  (/) y si no se tiene una sesión iniciada, se mostrará el formulario de inicio
  de sesión. En caso de tener una sesión, el usuario podrá acceder
  automáticamente a su página de perfil, donde se mostrará su foto y la opción
  de cambiar el color de la página.
